language: python
rvm:
  - 3.6

sudo: true

before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
- sudo apt-get update
- sudo apt-get install python3
virtualenv:
  system_site_packages: true

addons:
apt:
  packages:
    - "python3"
    - "python3-pip"

install:
  - pip3 install -r requirements.txt

script:
  - python3 start_tests.py