#language: python
#rvm:
#  - 3.6

sudo: false
dist: "trusty" # otherwise 'python3-pip' won't be available
language: "python"
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"

install:
  - pip3 install dash
  - pip install -r requirements.txt

script:
  - python3 start_tests.py