language: python
rvm:
  - 3.6

before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
virtualenv:
  system_site_packages: true

install:
  - pip install -r requirements.txt

script:
  - start_tests